#!/bin/sh -e

# navigate to local dir
cd "$(dirname "$0")"

# create venv if needed
if [ ! -d venv ]; then
    virtualenv -p python3 venv
fi
source venv/bin/activate

# install requirements if needed
if python -c 'import server'; then
    true
else
    pip install -r requirements.txt
fi

# open a browser
(sleep 1; open "http://localhost:${PORT:-8000}")

# run the server
./server.py
